spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    include: oauth

  data:
    web:
      pageable:
        one-indexed-parameters: true

  datasource:
    url: jdbc:h2:mem:blog
    username: sa
    password:
    driverClassName: org.h2.Driver

server:
  servlet:
    session:
      tracking-modes: cookie